### ISSUE TITLE
Create some additional issue labels

### ISSUE THREAD

**Issue by m-anish** [botlabio/autonomio#4]
Consider creating some additional issue labels on top of the basic ones already available

- testing (or QA, whatever is preferable)
- infrastructure (or something of that sort)

**Comment by mikkokotila** [comment]
Thanks. I've deleted some and then created a 4 stage priority:

- critical bug (where the bug is resulting in non-operation or unreliable output)
- bug (something is wrong but not necessarily limit operation and does not change output)
- must have (a feature that should be consider must have > have to define this clearly)
- nice to have (features that make sense, but are clearly not must have)

**Comment by m-anish** [comment]
Okay. Sounds good. Closing.
